name: Angular pipeline
on:
  workflow_call:
     inputs:
        dockerImage: 
           type: string
           required: true
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: building image 
          run: |
               pwsh -command 'Invoke-WebRequest -Uri "https://github.com/chaithragudimalla/Project/blob/main/.github/workflows/Dockerfile.txt" -OutFile "Dockerfile.txt"'
        - name: building docker image
          run: |
              ls -l
              readlink -f Dockerfile.txt
